name: strategy matrix

on:
    push:
        branches: [main]


jobs:
    py-version-print:
        runs-on: ubuntu-latest

        steps:
          - name: Set up Python 3.11
            uses: actions/setup-python@v5
            with:
                python-version: '3.11' # Install specific version

          - name: print python version
            run: |
                echo "Installed Python version is : "
                python -V