name: conditionals

on:
    # push:
    #     branches: [main]
    workflow_dispatch
jobs:
    condition:
        name: conditional
        runs-on: ubuntu-latest
        steps:
                - name: when main branch
                  id: main_branch
                  continue-on-error: true
                  if: github.ref_name == 'main'
                  run: |
                        eecho "Running due to push to $GITHUB_REF_NAME"

                - name: if previous failed
                  if: ${{ steps.main_branch.outcome == 'failure' }}
                  run: |
                        echo "running from upstream tasks!!"