name: conditionals

on:
    push:
        branches: [main]

jobs:
    condition:
        name: conditional
        runs-on: ubuntu-latest
        steps:
                - name: when main branch
                  if: github.ref_name == 'main'
                  run: |
                        echo "Running due to push to $GITHUB_REF_NAME"