name: flask-app

on:
  push:

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt

    - name: run the flask app
      id: app
      run: |
        python app.py

    - name: script execution check
      if: ${{ steps.app.outcome == 'failure' }}
      run: |
        exit 1
