name: generate-report

on:
    push:
        branches: [main]

jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - name: Generate Test Report
              run: |
                echo "Test Results - $(date)" > test-report.txt
                echo "Status: Passed" >> test-report.txt
                echo "Errors: 0" >> test-report.txt

            - name : Save the report
              uses: actions/upload-artifact@v4
              with:
                name: report-artifact
                path: test-report.txt
    print-report-content:
        runs-on: ubuntu-latest
        steps:
            - name: Download and print content of artifact
              uses: actions/download-artifact@v8
              with:
                name: report-artifact
                path: reports/

            - name: Print content of file
              run: |
                    cat reports/test-report.txt

            # - name: Print-contents
              