name: say hello

on:
    push:
        branches: [main]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: greet hello
              run: echo "Hello from GitHub Actions!"

            - name: print current date and time
              run: date

            - name: print triggered branch name
              run: echo "triggered branch name :" "$GITHUB_REF_NAME"

            - name: print triggered branch name
              run: 'echo "triggered branch name : $GITHUB_REF_NAME"'
              
            - name: print triggered branch name
              run: echo "triggered branch name :$GITHUB_REF_NAME"

            - name: print triggered branch name
              run: |
                  echo "triggered branch name : ${{ github.ref_name }}"

            - name: list files
              run: ls -a

            - name: Runner's OS
              run: echo "The OS is $RUNNER_OS"

            - name: incorrect command
              run: echi "echo mispelled"