name: print info in 3 os

on:
    push:
        branches: [main]



jobs:
    ubuntu-job:
        # strategy:
        #     matrix:
        #         os: ['ubuntu-latest','windows-latest','macos-latest']
        #echo "The OS name is: ${{ runner.os }}"
        # runs-on: ${{ matrix.os }}
        runs-on: ubuntu-latest
        steps:
            - name: print os name
              run: |
                    echo "The OS name is: ${{ runner.os }}"
            - name: Runner's hostname
              run: |
                    echo "hostname: $(hostname)"
            - name: Current User
              run: |
                    echo "Current User: $(whoami)"
            - name: tools-version 
              run: |
                    echo "Docker version is: $(docker --version)"
                    echo "Python version is: $(python -V)"
                    echo "Node version is: $(node -v)"
                    echo "Git version is: $(git --version)"


    macos-job:
        runs-on: macos-latest
        steps:
            - name: print os name
              run: |
                    echo "The OS name is: ${{ runner.os }}"
            - name: Runner's hostname
              run: |
                    echo "hostname: $(hostname)"
            - name: Current User
              run: |
                    echo "Current User: $(whoami)"
    
    windows-job:
        runs-on: windows-latest
        steps:
            - name: print os name
              run: |
                    echo "The OS name is: ${{ runner.os }}"
            - name: Runner's hostname
              run: |
                    echo "hostname: $(hostname)"
            - name: Current User
              run: |
                    echo "Current User: $(whoami)"