name: print-secret

on: 
    push:
        branch: main

jobs:
    print-secret:
        runs-on: ubuntu-latest
        steps:
            - name: printing secret value
              run : echo "The value inside secret is:${{ secrets.MY_SECRET_MESSAGE }}"