name: print-secret

on: 
    # push:
    #     branch: main
        workflow_dispatch
jobs:
    print-secret:
        runs-on: ubuntu-latest
        steps:
            - name: printing secret value
              env:
                    MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
              run : |
                    echo "The value inside secret is:${{ secrets.MY_SECRET_MESSAGE }}"
                    echo "Printing secrets as env var: $MY_SECRET_MESSAGE"